FROM adoptopenjdk/openjdk11:alpine-jre
LABEL maintainer = "coopint"

VOLUME /tmp

ADD target/jacoco-project-template.jar app.jar
ENTRYPOINT [ "sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]